// These styles apply to every route in the application
import './globals.css'
import { ThemeProvider } from "@/components/ui/theme-provider"
import { Toaster } from '@/components/ui/sonner'
import { ClerkProvider } from '@clerk/nextjs'
 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
             <Toaster />
           {children}
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
    
  )
}